name       : kmail
version    : 18.08.2
release    : 13
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.2/src/kmail-18.08.2.tar.xz : 46645d6174ec7ef769b6828848b65a07d2606b6a28f6650a46e56d8abd7cf565
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : network.mail
summary    : Email client, supporting POP3 and IMAP mailboxes
description: |
    KMail is the email component of Kontact, the integrated personal information manager from KDE.
builddeps  :
    - pkgconfig(libical)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5WebEngine)
    - akonadi-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - extra-cmake-modules
    - gpgme-qt-devel
    - kbookmarks-devel
    - kcalcore-devel
    - kcalutils-devel
    - kcmutils-devel
    - kcodecs-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdelibs4support-devel
    - kdepim-apps-libs-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kitemviews-devel
    - kitemmodels-devel
    - kjobwidgets-devel
    - kldap-devel
    - kmailtransport-devel
    - kmime-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kontactinterface-devel
    - kparts-devel
    - kpimtextedit-devel
    - kservice-devel
    - ktextwidgets-devel
    - ktnef-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libassuan-devel
    - libboost-devel
    - libgravatar-devel
    - libkdepim-devel
    - libkleo-devel
    - libksieve-devel
    - mailcommon-devel
    - messagelib-devel
    - openldap-devel
    - pimcommon-devel
    - sonnet-devel
    - syntax-highlighting-devel
rundeps    :
    - akonadi-import-wizard
    - kdepim-runtime
    - kleopatra
    - kmail-account-wizard
    - pim-data-exporter
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
