name       : kmail
version    : 22.04.3
release    : 66
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.3/src/kmail-22.04.3.tar.xz : b88101f47259a5ebfc4ec8e5d0efa19cdff33c67034e9c7082c22c0a11474d74
homepage   : https://apps.kde.org/kmail2/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-only
component  : network.mail
summary    : Email client, supporting POP3 and IMAP mailboxes
description: |
    KMail is the email component of Kontact, the integrated personal information manager from KDE.
builddeps  :
    - pkgconfig(Qt5WebEngine)
    - akonadi-search-devel
    - kcalendarcore-devel
    - kcalutils-devel
    - kcmutils-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kldap-devel
    - kmailtransport-devel
    - knotifyconfig-devel
    - kontactinterface-devel
    - kparts-devel
    - ktnef-devel
    - kuserfeedback-devel
    - libgravatar-devel
    - libksieve-devel
    - mailcommon-devel
    - openldap-devel
    - pimcommon-devel
    - qtkeychain-devel
rundeps    :
    - akonadi-import-wizard
    - kdepim-runtime
    - kleopatra
    - kmail-account-wizard
    - pim-data-exporter
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |-
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
