name       : kmail
version    : 20.04.3
release    : 40
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.3/src/kmail-20.04.3.tar.xz : 5b653c680097a7be4ff53bc902bc3fcda9edac99f699a63a1375a1df81240d03
homepage   : https://kde.org/applications/internet/org.kde.kmail
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-only
component  : network.mail
summary    : Email client, supporting POP3 and IMAP mailboxes
description: |
    KMail is the email component of Kontact, the integrated personal information manager from KDE.
builddeps  :
    - pkgconfig(libical)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5WebEngine)
    - akonadi-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - extra-cmake-modules
    - gpgme-qt-devel
    - kbookmarks-devel
    - kcalutils-devel
    - kcmutils-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdepim-apps-libs-devel
    - kdoctools-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kitemviews-devel
    - kitemmodels-devel
    - kldap-devel
    - kmailtransport-devel
    - kmime-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kontactinterface-devel
    - kparts-devel
    - kpimtextedit-devel
    - ktextwidgets-devel
    - ktnef-devel
    - kuserfeedback-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libboost-devel
    - libgravatar-devel
    - libkdepim-devel
    - libkleo-devel
    - libksieve-devel
    - mailcommon-devel
    - messagelib-devel
    - openldap-devel
    - pimcommon-devel
    - sonnet-devel
    - syntax-highlighting-devel
rundeps    :
    - akonadi-import-wizard
    - kdepim-runtime
    - kleopatra
    - kmail-account-wizard
    - pim-data-exporter
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |-
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
