name       : kmail
version    : 17.08.2
release    : 1
source     :
    - https://cdn.download.kde.org/stable/applications/17.08.2/src/kmail-17.08.2.tar.xz : a960fc8d8e30c633e1b87ad1eabf306f02e478b485da951f7186aaee90f6bd3b
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : network.mail
summary    : Email client, supporting POP3 and IMAP mailboxes
description: |
    KMail is the email component of Kontact, the integrated personal information manager from KDE.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libical)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5WebEngine)
    - akonadi-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - extra-cmake-modules
    - gpgme-qt-devel
    - kbookmarks-devel
    - kcalcore-devel
    - kcalutils-devel
    - kcmutils-devel
    - kcodecs-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdelibs4support-devel
    - kdepim-apps-libs-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kitemviews-devel
    - kitemmodels-devel
    - kjobwidgets-devel
    - kldap-devel
    - kmailtransport-devel
    - kmime-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kontactinterface-devel
    - kparts-devel
    - kpimtextedit-devel
    - kservice-devel
    - ktextwidgets-devel
    - ktnef-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libassuan-devel
    - libboost-devel
    - libgravatar-devel
    - libkdepim-devel
    - libkleo-devel
    - libksieve-devel
    - mailcommon-devel
    - messagelib-devel
    - openldap-devel
    - pimcommon-devel
    - sonnet-devel
    - syntax-highlighting-devel
rundeps    :
    - kdepim-runtime
    - kmail-account-wizard
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
