name       : kmail
version    : 20.12.2
release    : 49
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/kmail-20.12.2.tar.xz : 12ef9001bc570bb798a8c394214d8758554f88105c1611e09707190260732d26
homepage   : https://kde.org/applications/internet/org.kde.kmail
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-only
component  : network.mail
summary    : Email client, supporting POP3 and IMAP mailboxes
description: |
    KMail is the email component of Kontact, the integrated personal information manager from KDE.
builddeps  :
    - pkgconfig(Qt5WebEngine)
    - akonadi-search-devel
    - kcalendarcore-devel
    - kcalutils-devel
    - kcmutils-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kldap-devel
    - kmailtransport-devel
    - knotifyconfig-devel
    - kontactinterface-devel
    - kparts-devel
    - ktnef-devel
    - kuserfeedback-devel
    - libgravatar-devel
    - libksieve-devel
    - mailcommon-devel
    - openldap-devel
    - pimcommon-devel
rundeps    :
    - akonadi-import-wizard
    - kdepim-runtime
    - kleopatra
    - kmail-account-wizard
    - pim-data-exporter
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |-
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
